"""initial_schema

Revision ID: 98edea420e0c
Revises: 
Create Date: 2026-06-25 16:28:44.775768
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = '98edea420e0c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_pipeline_log',
    sa.Column('type', sa.Enum('Training', 'Inference', name='job_type'), nullable=False),
    sa.Column('model_task', sa.Enum('forecasting', 'anomaly_detection', 'prediction', name='model_task'), server_default='forecasting', nullable=False),
    sa.Column('mlflow_run_id', sa.String(), nullable=False),
    sa.Column('celery_task_id', sa.String(), nullable=True),
    sa.Column('datasource_used', sa.String(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Success', 'Failed', 'Running', 'Cancelled', name='job_status'), nullable=False),
    sa.Column('terminal_log', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('context_type',
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_type',
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drift_report',
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('mlflow_run_id', sa.String(), nullable=False),
    sa.Column('model_task', sa.Enum('forecasting', 'anomaly_detection', 'prediction', name='model_task'), nullable=False),
    sa.Column('drift_type', sa.Enum('data_drift', 'concept_drift', 'prediction_drift', name='drift_type'), nullable=False),
    sa.Column('feature_name', sa.String(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('drift_score', sa.Double(), nullable=False),
    sa.Column('drift_threshold', sa.Double(), nullable=False),
    sa.Column('is_drifted', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.Enum('none', 'low', 'medium', 'high', 'critical', name='drift_severity'), nullable=False),
    sa.Column('reference_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location_type',
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metric_type',
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_performance',
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('mlflow_run_id', sa.String(), nullable=False),
    sa.Column('model_task', sa.Enum('forecasting', 'anomaly_detection', 'prediction', name='model_task'), nullable=False),
    sa.Column('building_id', sa.String(), nullable=True),
    sa.Column('metric_type_id', sa.String(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('mae', sa.Double(), nullable=True),
    sa.Column('rmse', sa.Double(), nullable=True),
    sa.Column('mape', sa.Double(), nullable=True),
    sa.Column('r2_score', sa.Double(), nullable=True),
    sa.Column('mean_error', sa.Double(), nullable=True),
    sa.Column('p10_error', sa.Double(), nullable=True),
    sa.Column('p90_error', sa.Double(), nullable=True),
    sa.Column('baseline_mae', sa.Double(), nullable=True),
    sa.Column('baseline_rmse', sa.Double(), nullable=True),
    sa.Column('performance_ratio', sa.Double(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_log',
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('Admin', 'AI_Engineer', 'Operator', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('Available', 'In_Shift', 'Busy', 'On_Break', 'Off_Duty', 'On_Leave', 'Suspended', name='user_status'), nullable=False),
    sa.Column('contact_number', sa.String(), nullable=True),
    sa.Column('assigned_site_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_global_admin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('location',
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('location_type_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['location_type_id'], ['location_type.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anomaly_detected_event',
    sa.Column('building_id', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metric_type_id', sa.String(), nullable=False),
    sa.Column('primary_space_usage', sa.String(), nullable=True),
    sa.Column('actual_value', sa.Double(), nullable=True),
    sa.Column('predicted_value', sa.Double(), nullable=True),
    sa.Column('residual', sa.Double(), nullable=True),
    sa.Column('residual_z', sa.Double(), nullable=True),
    sa.Column('anomaly_score', sa.Double(), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('anomaly_type', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('mlflow_run_id', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['metric_type_id'], ['metric_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_id', 'timestamp', 'metric_type_id', 'source', name='uq_anomaly_detected_event')
    )
    op.create_table('context_data',
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('context_type_id', sa.String(), nullable=False),
    sa.Column('value', sa.Double(), nullable=False),
    sa.ForeignKeyConstraint(['context_type_id'], ['context_type.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'location_id', 'context_type_id')
    )
    op.create_table('device',
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('device_type_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['device_type_id'], ['device_type.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediction_log',
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('building_id', sa.String(), nullable=False),
    sa.Column('metric_type_id', sa.String(), nullable=False),
    sa.Column('predicted_value', sa.Double(), nullable=False),
    sa.Column('actual_value', sa.Double(), nullable=True),
    sa.Column('error', sa.Double(), nullable=True),
    sa.Column('mlflow_run_id', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('model_task', sa.Enum('forecasting', 'anomaly_detection', 'prediction', name='model_task'), nullable=False),
    sa.Column('feature_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prediction_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['metric_type_id'], ['metric_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anomaly_alert',
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('metric_type_id', sa.String(), nullable=False),
    sa.Column('severity', sa.Enum('Warning', 'Critical', 'Emergency', name='alert_severity'), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('Open', 'Acknowledged', 'Resolved', name='alert_status'), nullable=False),
    sa.Column('mlflow_run_id', sa.String(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['metric_type_id'], ['metric_type.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_metric_capability',
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('metric_type_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['metric_type_id'], ['metric_type.id'], ),
    sa.PrimaryKeyConstraint('device_id', 'metric_type_id')
    )
    op.create_table('forecast_result',
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('metric_type_id', sa.String(), nullable=False),
    sa.Column('predicted_value', sa.Double(), nullable=False),
    sa.Column('mlflow_run_id', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['metric_type_id'], ['metric_type.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'device_id', 'metric_type_id')
    )
    op.create_table('telemetry_data',
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('metric_type_id', sa.String(), nullable=False),
    sa.Column('value', sa.Double(), nullable=False),
    sa.Column('ingestion_status', sa.Enum('Success', 'Device_Error', 'Network_Timeout', name='ingestion_status'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['metric_type_id'], ['metric_type.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'device_id', 'metric_type_id')
    )
    op.create_table('threshold_config',
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('metric_type_id', sa.String(), nullable=False),
    sa.Column('baseline_value', sa.Double(), nullable=True),
    sa.Column('upper_limit', sa.Double(), nullable=True),
    sa.Column('lower_limit', sa.Double(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['metric_type_id'], ['metric_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('threshold_config')
    op.drop_table('telemetry_data')
    op.drop_table('forecast_result')
    op.drop_table('device_metric_capability')
    op.drop_table('anomaly_alert')
    op.drop_table('prediction_log')
    op.drop_table('device')
    op.drop_table('context_data')
    op.drop_table('anomaly_detected_event')
    op.drop_table('location')
    op.drop_table('users')
    op.drop_table('system_log')
    op.drop_table('model_performance')
    op.drop_table('metric_type')
    op.drop_table('location_type')
    op.drop_table('drift_report')
    op.drop_table('device_type')
    op.drop_table('context_type')
    op.drop_table('ai_pipeline_log')
    # ### end Alembic commands ###
